import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between p-2">
          <div className="bg-white w-10/12">
            <div className="mx-auto px-4 py-8 sm:px-6 sm:py-16 ">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
